In [1]:
##problema 1
import numpy as np
lista = [12.23, 13.32, 100, 36.32]
print("Original List:",lista)
array = np.array(lista)
print("One-dimensional numpy array: ",array)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array:  [ 12.23  13.32 100.    36.32]


In [2]:
##Problema 2
Vector_nulo = np.zeros(10)
print(Vector_nulo)
print("Update sixth value to 11")
Vector_nulo[6] = 11
print(Vector_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [3]:
##Problema 3
array = np.arange(12, 38)
print(array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [4]:
##Problema 4
arrayr = np.arange(12, 38)
print("Original array:")
print(arrayr)
print("Reverse array:")
arrayr = arrayr[::-1]
print(arrayr)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [5]:
##Problema 5
matrix = np.ones((5,5))
print("Original array:")
print(matrix)
print("1 on the border and 0 inside in the array")
matrix[1:-1,1:-1] = 0
print(matrix)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
##Problema 6
matrix = np.ones((3,3))
print("Checkerboard pattern:")
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
##Problema 7
f_values = [0, 12, 45.21, 34, 99.91]
F = np.array(f_values)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [8]:
##Problema 8
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70, 90]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70, 90]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [9]:
##Problema 9
matrix =  np.diagflat([4, 5, 6, 8])
print(matrix)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
